version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    command: uvicorn api.main:app --reload --workers 4 --host 0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - .:/juno_api
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
volumes:
  postgres_data: null
