version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    command: uvicorn app.main:app --reload --workers 4 --host 0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - .:/juno_api
    environment:
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_DIALECT=${DATABASE_DIALECT}
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=juno_db_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/juno_db_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./docker-entrypoint-initdb.d/init-test-database.sh:/docker-entrypoint-initdb.d/init-test-database.sh
    ports:
      - "5432:5432"
volumes:
  postgres_data: null

