"""initial migration

Revision ID: 13a62bac8967
Revises: 
Create Date: 2024-01-22 21:54:38.674593

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "13a62bac8967"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bill",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.DateTime(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category"],
            ["category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payment",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.Column("payment_date", sa.DateTime(), nullable=False),
        sa.Column("bill_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bill.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recurringbill",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("bill_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("recurrence_interval", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bill.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recurringbill")
    op.drop_table("payment")
    op.drop_table("bill")
    op.drop_table("category")
    # ### end Alembic commands ###
