"""update naming convention for auto_pay

Revision ID: 436378861552
Revises: 8de71851487e
Create Date: 2024-03-04 23:34:23.532072

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '436378861552'
down_revision = '8de71851487e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('auto_pay', sa.Boolean(), nullable=False))
    op.drop_column('bill', 'autoPay')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('autoPay', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('bill', 'auto_pay')
    # ### end Alembic commands ###
