"""add autopay column

Revision ID: 8de71851487e
Revises: a5e158cf8f43
Create Date: 2024-03-01 05:17:43.064563

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8de71851487e'
down_revision = 'a5e158cf8f43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('paid', sa.Integer(), nullable=True))
    op.add_column('bill', sa.Column('autoPay', sa.Boolean(), nullable=False))
    op.drop_column('bill', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('bill', 'autoPay')
    op.drop_column('bill', 'paid')
    # ### end Alembic commands ###
