"""add recurringbill table

Revision ID: 8f3082508e84
Revises: f34695f9ed54
Create Date: 2024-01-18 00:09:27.406818

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8f3082508e84'
down_revision = 'f34695f9ed54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurringbill',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('bill_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('recurrence_interval', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurringbill')
    # ### end Alembic commands ###
