"""add recurrance interval column

Revision ID: e1dbc485e705
Revises: d341c376b453
Create Date: 2023-12-28 01:11:34.761429

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e1dbc485e705'
down_revision = 'd341c376b453'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurringbill', sa.Column('recurrence_interval', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurringbill', 'recurrence_interval')
    # ### end Alembic commands ###
