def logger(text: str) -> None:
    print("==========")
    print("==========")
    print("==========")
    print(" ")
    print(" ")
    print(text)
    print(" ")
    print(" ")
    print("==========")
    print("==========")
    print("==========")
